[package]
name = "my-project"
version = "0.1.0"
authors = ["runner"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
harsh = "0.2.2"
rocket = "0.5.0-rc.2"
rocket_codegen = "0.4.11"
